// <auto-generated />
using Application.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Application.Persistance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210825124948_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14");

            modelBuilder.Entity("Domain.Model.Entities.GameEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayUIGameName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(450);

                    b.Property<string>("WindowGameName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(450);

                    b.HasKey("Id");

                    b.ToTable("GameEntities");
                });

            modelBuilder.Entity("Domain.Model.Entities.GameKeyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeyId_FK")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeyModifierId_FK")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetKey_FK")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WindowGameNameId_FK")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KeyId_FK");

                    b.HasIndex("KeyModifierId_FK");

                    b.HasIndex("TargetKey_FK");

                    b.HasIndex("WindowGameNameId_FK");

                    b.ToTable("GameKeysEntities");
                });

            modelBuilder.Entity("Domain.Model.Entities.KeyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(450);

                    b.HasKey("Id");

                    b.ToTable("KeysEntities");
                });

            modelBuilder.Entity("Domain.Model.Entities.KeyModifierEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(450);

                    b.Property<string>("KeyModifier")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(450);

                    b.HasKey("Id");

                    b.ToTable("KeyModifierEntities");
                });

            modelBuilder.Entity("Domain.Model.Entities.GameKeyEntity", b =>
                {
                    b.HasOne("Domain.Model.Entities.KeyEntity", "KeyEntity")
                        .WithMany("GameKeysEntity")
                        .HasForeignKey("KeyId_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Model.Entities.KeyModifierEntity", "KeyModifierEntity")
                        .WithMany("GameKeysEntity")
                        .HasForeignKey("KeyModifierId_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Model.Entities.KeyEntity", "TargetKeyEntity")
                        .WithMany("GameTargetKeysEntity")
                        .HasForeignKey("TargetKey_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Model.Entities.GameEntity", "GameEntity")
                        .WithMany("GameKeysEntity")
                        .HasForeignKey("WindowGameNameId_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
